apiVersion: v1
kind: Service
metadata:
  name: {{ include "mydrive.fullname" . }}
  labels:
    {{- include "mydrive.labels" . | nindent 4 }}
  annotations:
    "oneclick-saas.io/serviceIngressPath": "/:80"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mydrive.selectorLabels" . | nindent 4 }}
